import {
  faFistRaised,
  faDragon,
  faPaintBrush,
  faUtensilSpoon,
  faHammer,
  faFemale,
  faTshirt,
  faDumbbell,
  faPizzaSlice,
  faGamepad,
  faSeedling,
  faCampground,
  faFilm,
  faMusic,
  faMoon,
  faCat,
  faBookOpen,
  faPrayingHands,
  faFutbol,
  faMicrochip,
  faTheaterMasks,
  faPlane,
  faUndo,
  faComments,
  faTimes,
  faStar,
  faDoorOpen,
  faCog,
  faTh,
  faCheck,
  faEnvelope,
  faUserCircle,
} from "@fortawesome/free-solid-svg-icons";

import { faStar as faStarRegular } from "@fortawesome/free-regular-svg-icons";

const icons = {
  buttonDict: {
    faUndo,
    faComments,
    faTimes,
    faStar,
    faDoorOpen,
    faCog,
    faTh,
    faCheck,
    faEnvelope,
    faStarRegular,
  },

  faUserCircle,

  interestDict: {
    Activism: faFistRaised,
    Animals: faCat,
    Anime: faDragon,
    Art: faPaintBrush,
    Cooking: faUtensilSpoon,
    Crafting: faHammer,
    Drag: faFemale,
    Fashion: faTshirt,
    Fitness: faDumbbell,
    Food: faPizzaSlice,
    Gaming: faGamepad,
    Gardening: faSeedling,
    Movies: faFilm,
    Music: faMusic,
    Nightlife: faMoon,
    Outdoors: faCampground,
    Reading: faBookOpen,
    Spirituality: faPrayingHands,
    Sports: faFutbol,
    Tech: faMicrochip,
    Theater: faTheaterMasks,
    Travel: faPlane,
  },
};

export default icons;
